# Generated by Django 3.2.5 on 2021-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honeypot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honeypotType', models.CharField(choices=[('FTP', 'CanaryFTP'), ('SSH', 'CanarySSH')], max_length=10)),
            ],
        ),
    ]
