# Generated by Django 3.2.5 on 2021-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypot',
            name='honeypotIP',
            field=models.CharField(default='', max_length=15),
        ),
    ]
