# Generated by Django 3.2.5 on 2021-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot_app', '0002_honeypot_honeypotip'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypot',
            name='activeStatus',
            field=models.BooleanField(default=True),
        ),
    ]
