# Generated by Django 3.2.5 on 2021-07-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot_app', '0004_alter_honeypot_honeypotip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeypot',
            name='activeStatus',
        ),
    ]
