# Generated by Django 3.2.6 on 2021-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot_app', '0005_remove_honeypot_activestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeypot',
            name='honeypotType',
            field=models.CharField(choices=[('FTP', 'CanaryFTP'), ('SSH', 'CanarySSH'), ('HTTP', 'CanaryHTTP')], max_length=10),
        ),
    ]
